; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.6.0-STM32+1 on Wed Jun 03 2026 11:13:59 GMT+0200 (Centraleuropæisk sommertid)
;M561 ; clear any bed transform
;G29  ; probe the bed and enable compensation


