; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool v3.6.0-STM32+1 on Wed Jun 03 2026 11:14:00 GMT+0200 (Centraleuropæisk sommertid)
G91               ; relative positioning
G1 H1 X-490 F500 ; move quickly to X axis endstop
G1 H2 X5 F500    ; go back a few mm
G1 H1 X-490 F360  ; move slowly to X axis endstop
G1 H2 X5 F500     ; lidt frem
G92 X0            ; sæt det som X 0 så fri af gaffel
G90               ; absolute positioning

