; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.6.0-STM32+1 on Wed Jun 03 2026 11:14:02 GMT+0200 (Centraleuropæisk sommertid)

