; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.6.0-STM32+1 on Sun May 03 2026 15:00:20 GMT+0200 (Centraleuropæisk sommertid)
; Wait for set temperatures to be reached


